import "./globals.css";
import Nav from "@/components/mainnav";
import Providers from "@/components/Providers";

export const metadata = {
  title: "Juman Store | Online shopping",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" bg-slate-100 ">
        <Providers>
          <Nav />
          <div className="max-w-screen-2xl m-auto shadow-xl p-0 md:p-4 bg-blue-300 min-h-screen">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
