services:
  - type: web_service
    name: threads-replica
    env: node
    build_command: npm install && npm install --prefix frontend && npm run build --prefix frontend
    start_command: npm run start
    branch: main
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        value: mongodb+srv://brianmichaeladero:sundugweno@cluster0.cvl2fih.mongodb.net/Threads?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        value: jwtSecret
      - key: CLOUDINARY_CLOUD_NAME
        value: djega3cvv
      - key: CLOUDINARY_API_KEY
        value: 372266321518956
      - key: CLOUDINARY_API_SECRET
        value: B2Gy-FNcK9JUad06BgefRxZPEwI
